markdown: rdiscount
pygments: true
#permalink: :categories/:year/:month/:day/:title 
permalink: :categories/:title 
title : 会飞de树's Blog
author :
  name : 会飞de树
  email : wellwy@gmail.com
  github : wellwy
  twitter : 
  feedburner : 

baseurl : /Blog
homepage : /index.html
graphs : /Blog/include/graphs

comments: true