markdown: redcarpet
pygments: true
permalink: /:categories/:year/:month/:day/:title 
title : 会飞de树's Blog
author :
  name : 会飞de树
  email : wellwy@gmail.com
  github : wellwy
  twitter : 
  feedburner : 


basepath : http://wellwy.github.io/Blog